const VideoData = [
  {
    id: 1,
    channel: "Channel Name",
    channel_img: "https://picsum.photos/seed/picsum/500/500",
    title: "Video Title",
    views: "1.2M",
    time: "2 years ago",
    img: "https://picsum.photos/seed/picsum/1920/1080",
    link: "/",
  },
  {
    id: 2,
    channel: "Channel Name",
    channel_img: "https://picsum.photos/seed/picsum/500/500",
    title: "Video Title",
    views: "1.2M",
    time: "2 years ago",
    img: "https://picsum.photos/seed/picsum/1920/1080",
    link: "/",
  },
  {
    id: 3,
    channel: "Channel Name",
    channel_img: "https://picsum.photos/seed/picsum/500/500",
    title: "Video Title",
    views: "1.2M",
    time: "2 years ago",
    img: "https://picsum.photos/seed/picsum/1920/1080",
    link: "/",
  },
  {
    id: 4,
    channel: "Channel Name",
    channel_img: "https://picsum.photos/seed/picsum/500/500",
    title: "Video Title",
    views: "1.2M",
    time: "2 years ago",
    img: "https://picsum.photos/seed/picsum/1920/1080",
    link: "/",
  },
  {
    id: 5,
    channel: "Channel Name",
    channel_img: "https://picsum.photos/seed/picsum/500/500",
    title: "Video Title",
    views: "1.2M",
    time: "2 years ago",
    img: "https://picsum.photos/seed/picsum/1920/1080",
    link: "/",
  },
  {
    id: 6,
    channel: "Channel Name",
    channel_img: "https://picsum.photos/seed/picsum/500/500",
    title: "Video Title",
    views: "1.2M",
    time: "2 years ago",
    img: "https://picsum.photos/seed/picsum/1920/1080",
    link: "/",
  },
  {
    id: 7,
    channel: "Channel Name",
    channel_img: "https://picsum.photos/seed/picsum/500/500",
    title: "Video Title",
    views: "1.2M",
    time: "2 years ago",
    img: "https://picsum.photos/seed/picsum/1920/1080",
    link: "/",
  },
  {
    id: 8,
    channel: "Channel Name",
    channel_img: "https://picsum.photos/seed/picsum/500/500",
    title: "Video Title",
    views: "1.2M",
    time: "2 years ago",
    img: "https://picsum.photos/seed/picsum/1920/1080",
    link: "/",
  },
  {
    id: 9,
    channel: "Channel Name",
    channel_img: "https://picsum.photos/seed/picsum/500/500",
    title: "Video Title",
    views: "1.2M",
    time: "2 years ago",
    img: "https://picsum.photos/seed/picsum/1920/1080",
    link: "/",
  }
]

export default VideoData;